# Generated by Django 3.2.6 on 2021-09-06 18:52

from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('patronymic', models.CharField(blank=True, max_length=200, null=True)),
                ('surname', models.CharField(db_index=True, max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=19)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=employees.models.employees_photo_directory_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
